### ISSUE TITLE
PS3 Build

### ISSUE THREAD

**Issue by humbertodias** [kazzmir/paintown#91]
I've notice that ps3 build were made through SCons and python.
https://github.com/kazzmir/paintown/releases/download/v3.6.0/paintown-ps3-3.6.0.pkg
Should we keep that way or try something new?

if so, do you remember steps?

I was looking at ps3toolchain : https://github.com/ps3dev/ps3toolchain

**Comment by juvinious** [comment]
You would need to build from the 3.6 source. 
The instructions can be found under doc/ps3. 
If it works/builds still is a wild guess though. 

Allot of the mugen stuff was very preliminary and experimental in that release.

**Comment by kazzmir** [comment]
We should use meson to build. I doubt the ps3 stuff will work anymore. Maybe we could test it in an emulator or something if there are any good ones.

**Comment by humbertodias** [comment]
> We should use meson to build. I doubt the ps3 stuff will work anymore. Maybe we could test it in an emulator or something if there are any good ones.

I have tested the release 3.6.0 on RPCS3 and it works well.
![Screenshot 2024-02-15 at 10 37 00 PM](https://github.com/kazzmir/paintown/assets/9255997/cc8e0be7-8425-4df2-8336-51841cf9bdc6)

**Comment by humbertodias** [comment]
> You would need to build from the 3.6 source. The instructions can be found under doc/ps3. If it works/builds still is a wild guess though.
> 
> Allot of the mugen stuff was very preliminary and experimental in that release.

Makes sense. I'm gonna try to build the pkg using docker as a cross compiler such as you did previously with mingw

**Comment by kazzmir** [comment]
Thats cool that it works on RPCS3. The latest version of paintown now requires c++11 and threading support in gcc, so I'm not sure if the PS3 sdk PSL1ght supports that.

**Comment by humbertodias** [comment]
> Thats cool that it works on RPCS3. The latest version of paintown now requires c++11 and threading support in gcc, so I'm not sure if the PS3 sdk PSL1ght supports that.

It's almost working. I have created the container with embedded ps3toolchain and it comes with compiled sdl1.2. Now it's needed to add the sdl2 and other paintown dependencies. Teorically, after that we should to be ready to compile and package.

**Comment by juvinious** [comment]
Once it's building and you are able to generate a pkg we should migrate the environment over from Scons to Meson.

**Comment by humbertodias** [comment]
> Once it's building and you are able to generate a pkg we should migrate the environment over from Scons to Meson.

Perfect. We already have a ps3 package from a simple c++ sdl2
```shell
./easy-compile-docker-ps3 && ./release/release-ps3
```
![image](https://github.com/kazzmir/paintown/assets/9255997/ada79116-c090-497e-8004-18be14da8d87)

**Comment by juvinious** [comment]
Ok got it to work. Had to change the files since the ones you uploaded were uppercase.
![image](https://github.com/kazzmir/paintown/assets/581120/921fa731-aef8-441f-9f94-36087ec6969c)
Also added an argument to allow for a different data directory.

**Comment by juvinious** [comment]
Ah ok, now it makes sense.

**Comment by humbertodias** [comment]
> Ah ok, now it makes sense.

The error occurred while attempting to compile yaml-cpp using psp-g++
Same for ps3-dev
### How to reproduce
```shell
docker run --platform=linux/amd64 --rm -i -v `mktemp -d`:/source pspdev/pspdev:latest sh -s <<EOF
wget https://github.com/jbeder/yaml-cpp/archive/refs/tags/0.8.0.tar.gz
tar xvfz 0.8.0.tar.gz
cd yaml-cpp-0.8.0
env
mkdir -p build 
cd build
cmake -Wno-dev -DCMAKE_TOOLCHAIN_FILE=/usr/local/pspdev/psp/share/pspdev.cmake \
-DCMAKE_INSTALL_PREFIX=/usr/local/pspdev/psp -DBUILD_SHARED_LIBS=OFF ..
make 
make install
EOF
```
### Error
```
- Build files have been written to: /yaml-cpp-0.8.0/build
[  2%] Building CXX object CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilder.cpp.obj
cc1plus: error: cannot generate position-independent code for ‘-mabi=eabi’
make[2]: *** [CMakeFiles/yaml-cpp.dir/build.make:76: CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilder.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:861: CMakeFiles/yaml-cpp.dir/all] Error 2
```

**Comment by juvinious** [comment]
Easy solution is too not include yaml. It's not required.

**Comment by humbertodias** [comment]
> The error suggests a general issue with compiling for a specific abi though, should we remove that -meabi flag?

Yeah. Even removing, fail. weird.

**Comment by humbertodias** [comment]
> Easy solution is to not include yaml. It's not required. Make sure -DHAVE_YAML is not set.

i'm gonna try

**Comment by humbertodias** [comment]
> Easy solution is to not include yaml. It's not required. Make sure -DHAVE_YAML is not set.

I found the problem and submitted a fix https://github.com/jbeder/yaml-cpp/pull/1271

**Comment by juvinious** [comment]
Cool, hopefully they accept it but I bet they'll ask for something more generic (i.e. not ps3/psp) to check. But who knows. 
What I did was just not include yaml support for now for the dkp build by checking if it was downloaded or not:

```python
if meson.is_cross_build()
  fs = import('fs')
  if fs.is_dir('.tmp/yaml-cpp')
    add_global_arguments('-DHAVE_YAML_CPP', language: 'cpp')
    subdir('.tmp/yaml-cpp')
  endif
  subdir('.tmp/SDL_gfx')
endif
```

**Comment by kazzmir** [comment]
We could apply a local patch to the yaml code, if upstream won't accept a change

**Comment by humbertodias** [comment]
> We could apply a local patch to the yaml code, if upstream won't accept a change

Good idea!
I have overpass the yaml-cpp problem.
Now another with r-tech1/libgme
How to reproduce
```shell
git clone https://github.com/kazzmir/paintown -b build-psp
cd paintown
./easy-compile-docker-psp
```
Error
https://github.com/kazzmir/paintown/actions/runs/7994410565/job/21832385288?pr=93#step:3:10345
```
  User defined options
    Cross files: psp-cross.txt

Found ninja-1.11.1 at /usr/bin/ninja
(cd build-psp; meson configure -Dbuild_tests=false)
meson compile  -C build-psp
ninja: Entering directory `/paintown-bin/build-psp'
[1/352] Compiling C++ object src/r-tech1/libs/gme/libgme.a.p/Ay_Apu.cpp.o
[2/352] Compiling C++ object src/r-tech1/libs/gme/libgme.a.p/Data_Reader.cpp.o
[3/352] Compiling C++ object src/r-tech1/libs/gme/libgme.a.p/Ay_Cpu.cpp.o
FAILED: src/r-tech1/libs/gme/libgme.a.p/Ay_Cpu.cpp.o 
psp-g++ -Isrc/r-tech1/libs/gme/libgme.a.p -Isrc/r-tech1/libs/gme -I../src/r-tech1/libs/gme -Isrc -I../src -I/psp/include -I/pspdev/psp/include -I/pspdev/psp/sdk/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++11 -O0 -g -DUSE_SDL2=1 '-DDATA_PATH="data"' -g3 -Wextra -Wno-unused-variable -Wno-unused-function -Wno-unused-parameter -DHAVE_OGG=1 -DHAVE_MP3_MPG123=1 -DPSP -D_PSP_FW_VERSION=500 -w -MD -MQ src/r-tech1/libs/gme/libgme.a.p/Ay_Cpu.cpp.o -MF src/r-tech1/libs/gme/libgme.a.p/Ay_Cpu.cpp.o.d -o src/r-tech1/libs/gme/libgme.a.p/Ay_Cpu.cpp.o -c ../src/r-tech1/libs/gme/Ay_Cpu.cpp
../src/r-tech1/libs/gme/Ay_Cpu.cpp:104:10: error: #error "Byte order of CPU must be known"
  104 |         #error "Byte order of CPU must be known"
      |          ^~~~~
../src/r-tech1/libs/gme/Ay_Cpu.cpp: In member function ‘bool Ay_Cpu::run(cpu_time_t)’:
../src/r-tech1/libs/gme/Ay_Cpu.cpp:413:24: error: ‘R8’ was not declared in this scope; did you mean ‘RL’?
  413 |                 data = R8( opcode & 7, 0 );
      |                        ^~
      |                        RL
[4/352] Compiling C++ object src/r-tech1/libs/gme/libgme.a.p/Classic_Emu.cpp.o
```

**Comment by kazzmir** [comment]
https://en.wikipedia.org/wiki/PlayStation_Portable_hardware

Looks like the PSP is little endian. We just have to define BLARGG_LITTLE_ENDIAN in gme/blargg_endian.h for the PSP

**Comment by kazzmir** [comment]
Well this github issue is supposed to be about the ps3 build, but now we are discussing psp. Maybe we should move psp discussion to its own issue?

**Comment by humbertodias** [comment]
> Well this github issue is supposed to be about the ps3 build, but now we are discussing psp. Maybe we should move psp discussion to its own issue?

Oh.. that's true. I'm gonna create another issue for psp

**Comment by humbertodias** [comment]
> https://en.wikipedia.org/wiki/PlayStation_Portable_hardware
> 
> Looks like the PSP is little endian. We just have to define BLARGG_LITTLE_ENDIAN in gme/blargg_endian.h for the PSP

Fixed https://github.com/kazzmir/paintown/pull/93/commits/e0f5bcbe4db2aad14c3baa5f9e832c7561105999

**Comment by humbertodias** [comment]
> Cool, hopefully they accept it but I bet they'll ask for something more generic (i.e. not ps3/psp) to check. But who knows. What I did was just not include yaml support for now for the dkp build by checking if it was downloaded or not:
> 
> ```python
> if meson.is_cross_build()
>   fs = import('fs')
>   if fs.is_dir('.tmp/yaml-cpp')
>     add_global_arguments('-DHAVE_YAML_CPP', language: 'cpp')
>     subdir('.tmp/yaml-cpp')
>   endif
>   subdir('.tmp/SDL_gfx')
> endif
> ```

Merged https://github.com/jbeder/yaml-cpp/pull/1271

**Comment by humbertodias** [comment]
Unfortunately the container [PSL1GHT](https://github.com/ps3dev/PSL1GHT) doesn't include SDL2_image|ttf|mixer|glx and I'm gonna add on [ps3libraries](https://github.com/ps3dev/ps3libraries/issues/65)

**Comment by humbertodias** [comment]
> Unfortunately the container [PSL1GHT](https://github.com/ps3dev/PSL1GHT) doesn't include SDL2_image|ttf|mixer|glx and I'm gonna add on [ps3libraries](https://github.com/ps3dev/ps3libraries/issues/65)

Image [ps3dev-sdl2](https://github.com/humbertodias/ps3dev-sdl2) created

### Content: 

[SDL_PSL1GHT](https://github.com/zeldin/SDL_PSL1GHT) + [SDL_PSL1GHT_Libs](https://github.com/zeldin/SDL_PSL1GHT_Libs)
* sdl - 1.3.0
* sdl_mixer - 1.2.11
* sdl_image - 1.2.10
* sdl_ttf - 2.0.10
* sdl_net - 1.2.7
* sdl_gfx - 2.0.27

[SDL2_PSL1GHT](https://github.com/humbertodias/SDL2_PSL1GHT)  + [SDL2_PSL1GHT_Libs](https://github.com/humbertodias/SDL2_PSL1GHT_Libs)
* sdl2 - 2.0.13
* sdl2_mixer - 2.8.0
* sdl2_image - 2.8.2
* sdl2_ttf - 2.22.0
* sdl2_gfx - 2.22.0

**Comment by humbertodias** [comment]
Are we going to use pthread instead of std:thread?
I have already compiled pthread inside ps3 container.
```
[143/361] Compiling C++ object src/r-tech1/libr-tech1.a.p/graphics_bitmap.cpp.o
FAILED: src/r-tech1/libr-tech1.a.p/graphics_bitmap.cpp.o 
ppu-g++ -Isrc/r-tech1/libr-tech1.a.p -Isrc/r-tech1 -I../paintown-bin/src/r-tech1 -Isrc -I../paintown-bin/src -I/usr/local/ps3dev/portlibs/ppu/include/SDL2 -I/usr/local/ps3dev/portlibs/ppu/include -I/usr/local/include -I/usr/local/ps3dev/ppu/include/ -I/usr/local/ps3dev/portlibs/ppu/include/ -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++11 -O0 -g -DUSE_SDL2=1 -g3 -Wextra -Wno-unused-variable -Wno-unused-function -Wno-unused-parameter -DCROSS_BUILD -DHAVE_OGG=1 -mhard-float -fmodulo-sched -ffunction-sections -fdata-sections -maltivec -mminimal-toc -DPS3 -DHAVE_YAML_CPP -mcpu=cell -fno-builtin -nostdlib '-DDATA_PATH="/dev_hdd0/game/paintown/data"' -fPIC -MD -MQ src/r-tech1/libr-tech1.a.p/graphics_bitmap.cpp.o -MF src/r-tech1/libr-tech1.a.p/graphics_bitmap.cpp.o.d -o src/r-tech1/libr-tech1.a.p/graphics_bitmap.cpp.o -c ../paintown-bin/src/r-tech1/graphics/bitmap.cpp
In file included from ../paintown-bin/src/r-tech1/file-system.h:6:0,
                 from ../paintown-bin/src/r-tech1/funcs.h:10,
                 from ../paintown-bin/src/r-tech1/graphics/bitmap.cpp:1:
../paintown-bin/src/r-tech1/thread.h:180:10: error: 'thread' in namespace 'std' does not name a type
     std::thread thread;
          ^~~~~~
../paintown-bin/src/r-tech1/thread.h:296:10: error: 'thread' in namespace 'std' does not name a type
     std::thread thread;
          ^~~~~~
../paintown-bin/src/r-tech1/thread.h: In destructor 'virtual Util::Future<X>::~Future()':
../paintown-bin/src/r-tech1/thread.h:219:13: error: 'thread' was not declared in this scope
```

**Comment by kazzmir** [comment]
it would be nice if we could continue to use std::thread, and have std::thread use some native thread implementation, or perhaps use sdl2's threading system. if that doesn't work then maybe I will write some wrapper around std::thread that can use whatever the native threading system is for each port

**Comment by kazzmir** [comment]
what version of g++ is ppu-g++ based off of? if ppu-g++ is something recent, like gcc 11 then I would expect std::thread to be there. if not, maybe ppu-g++ can be updated?

**Comment by humbertodias** [comment]
> what version of g++ is ppu-g++ based off of? if ppu-g++ is something recent, like gcc 11 then I would expect std::thread to be there. if not, maybe ppu-g++ can be updated?
7.2.0
```sh
DOCKER_DEFAULT_PLATFORM=linux/amd64 docker run -it hldtux/ps3dev-sdl2 bash -c "ppu-gcc --version"
ppu-gcc (GCC) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by humbertodias** [comment]
> > what version of g++ is ppu-g++ based off of? if ppu-g++ is something recent, like gcc 11 then I would expect std::thread to be there. if not, maybe ppu-g++ can be updated?
> 
> We are using the toolchain https://github.com/ps3dev/ps3toolchain I found out a newer version - 13.2.0-1 https://aur.archlinux.org/packages/ps3-ppu-gcc
> 
> it's adapted for archlinux but, they have left the patch <img alt="image" width="666" src="https://private-user-images.githubusercontent.com/9255997/309917833-7752d7ac-aa14-43e2-88d0-1af0ded63d9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTc3MDUsIm5iZiI6MTcwOTY5NzQwNSwicGF0aCI6Ii85MjU1OTk3LzMwOTkxNzgzMy03NzUyZDdhYy1hYTE0LTQzZTItODhkMC0xYWYwZGVkNjNkOWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMDM1NjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWQyODNhMTJjNTgxZWVkNjQxNDY1YzY2YjMwZTI0MzUwN2E2YTVhMTliZGFkYWIyMzBjYzA5YzJkYjk5Nzc0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.APD0Xc6oq9kZ4Xfx10WLu2GP0Ff6lGiKMYRu5EaKJ3c"> I'm gonna build gcc 13.2 with that patch and later on try to compile paintown with std:thread

PR - Upgrading https://github.com/ps3dev/ps3toolchain/pull/121
* GNU Binutils 2.42
* ppu-gcc (GCC) 13.2.0
* spu-gcc (GCC) 9.5.0

Now we can retry to compile paintown with c11 feature std::thread

**Comment by humbertodias** [comment]
Success! 
After upgrading ppu-gcc to 13 we have support to std:thread
```shh
[353/361] Compiling C++ object src/openbor/libopenbor.a.p/display-character.cpp.o
[354/361] Compiling C++ object src/openbor/libopenbor.a.p/pack-reader.cpp.o
[355/361] Compiling C++ object paintown.p/src_globals.cpp.o
[356/361] Compiling C++ object paintown.p/src_factory_collector.cpp.o
[357/361] Compiling C++ object paintown.p/src_factory_font_render.cpp.o
[358/361] Compiling C++ object src/openbor/libopenbor.a.p/mod.cpp.o
[359/361] Linking static target src/openbor/libopenbor.a
[360/361] Compiling C++ object paintown.p/src_main-menu.cpp.o
[361/361] Linking target paintown
```
Now it's remaining only runtime issues
![image](https://github.com/kazzmir/paintown/assets/9255997/ebae4a63-4ed8-43ce-a356-0ff4f8c0095f)

**Comment by kazzmir** [comment]
Awesome! How far does the game get at runtime? Does the menu show up?

**Comment by humbertodias** [comment]
I have anticipated myself.
Even with c11 enabled the use of thread and lambda are not compiling.
Here for example https://github.com/kazzmir/paintown/actions/runs/8181132738/job/22370408154?pr=92#step:3:318
```
../paintown-bin/src/r-tech1/sound/music.cpp: In constructor 'Music::Music(bool)':
../paintown-bin/src/r-tech1/sound/music.cpp:57:50: error: no matching function for call to 'std::thread::thread(void (&)(Music*), Music*)'
   57 |         musicThread = std::thread(playMusic, this);
```

**Comment by humbertodias** [comment]
I think i understood what is going on.
Let me try to explain and if you are gonna say if it makes sense or not.

Paintown uses std::thread with c11 that is Object-Oriented and pthread-emb library inside the container is compiled only in c as procedural here [pthread-emb-ps3](https://github.com/humbertodias/pthread-emb-ps3)

I think the problem is that. 
pthread-embps3 should be Object-Oriented as well to match and also be compiled with g++ here [039-pthread-emb.sh ](https://github.com/humbertodias/ps3libraries/blob/master/scripts/039-pthread-emb.sh)

Example

procedural.c
```c
#include <stdio.h>
#include <pthread.h>
#include <unistd.h> // For sleep() function

void* thread_function(void* arg) {
    int thread_num = *((int*)arg);
    printf("Thread %d is running\n", thread_num);
    sleep(1); // Simulate some work
    printf("Thread %d finished\n", thread_num);
    return NULL;
}

int main() {
    pthread_t thread1, thread2;
    int thread1_num = 1, thread2_num = 2;

    // Create threads
    pthread_create(&thread1, NULL, thread_function, (void*)&thread1_num);
    pthread_create(&thread2, NULL, thread_function, (void*)&thread2_num);

    // Wait for threads to finish
    pthread_join(thread1, NULL);
    pthread_join(thread2, NULL);

    printf("Both threads have finished\n");

    return 0;
}
```

```sh
gcc -std=c11 -pthread procedural -o procedural
```


oo.cpp

```cpp
#include <iostream>
#include <thread>

// Function to be executed by the thread
void threadFunction(int threadID) {
    std::cout << "Thread " << threadID << " is executing" << std::endl;
}

int main() {
    // Creating a thread and passing a function to execute
    std::thread t1(threadFunction, 1);

    // Joining the thread to the main thread
    t1.join();

    // Output a message from the main thread
    std::cout << "Main thread is executing" << std::endl;

    return 0;
}
```

```sh
g++ -std=c11 -pthread oo.cpp -o oo
```

Does it make sense for you?

**Comment by kazzmir** [comment]
If you are compiling c++ code try adding `-std=c++11` instead of `-std=c11`. But essentially std::thread should be implemented on top of pthread.

**Comment by humbertodias** [comment]
> If you are compiling c++ code try adding `-std=c++11` instead of `-std=c11`. But essentially std::thread should be implemented on top of pthread.

I have solved using Util::Thread instead. 
Now we have the compilation working again. But on runtime it freezes and got stuck on a black screen. 
I'm almost sure that something is missing on ps3dev and I'm still investigating
